version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: redis
    versions:
    - 3.1.2
  - dependency-name: "@types/node"
    versions:
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: eslint
    versions:
    - 7.23.0
    - 7.24.0
  - dependency-name: ioredis
    versions:
    - 4.24.5
    - 4.24.6
    - 4.25.0
    - 4.26.0
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.12
    - 7.13.15
  - dependency-name: firebase-admin
    versions:
    - 9.6.0
  - dependency-name: "@babel/register"
    versions:
    - 7.13.14
  - dependency-name: "@types/jest"
    versions:
    - 26.0.22
  - dependency-name: pug-code-gen
    versions:
    - 3.0.2
